### ISSUE TITLE
Add `-fshort-enums` / `-fno-short-enums` option

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#133]
This can be used to control the size of enums:

`-fshort-enums: Allocate to an enum type only as many bytes as it needs for the declared range of possible values`

example:
```c
#include <stdio.h>
enum E { A, B};
int main(void) {
    printf("%zu\n", sizeof(enum E));
    return 0;
}
```

Compiled with `-fshort-enums` on my system, the output is `1`; without the flag the output is `4`.

**Comment by Vexu** [comment]
I added the option in e690a97c7e192338f71ea5f186fd133d674ee572 but the actual mechanism to get it to function properly still needs some work.
