### ISSUE TITLE
Crash: unterminated string constant

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#135]
The attached code tricks the preprocessor into producing a file with an unterminated string constant, which results in a null pointer access in `Parser.stringLiteral`. The macro on line 6 only contains a `\r` between the closing paren and `vers` - be careful saving it with a text editor since it may "helpfully" do newline conversion for you and prevent the crash (filename ends in .txt since Github won't let me use a `.c` extension)

[unterminated string.txt](https://github.com/Vexu/arocc/files/7610848/unterminated.string.txt)

`arocc -E` output:

```C
void foo ( void ) { "
}
```

**Comment by ehaas** [comment]
clang treats `\r`, `\n`, and `\r\n` as possible line endings (`Lexer::LexTokenInternal` in `clang/lib/Lex/Lexer.cpp`). Updating Tokenizer to behave the same way makes this crash go away but I'm not sure if that's the right solution or just hiding the problem.

**Comment by Vexu** [comment]
`\r` was the line ending in a bunch of [old sytems](https://en.wikipedia.org/wiki/Newline#Representation) so adding it is valid, though I highly doubt it will ever be encountered in a real world situation.

**Comment by Vexu** [comment]
Regressed by #65.

**Comment by Vexu** [comment]
This no longer crashes.
