### ISSUE TITLE
Attributes are not parsed for record fields

### ISSUE THREAD

**Issue by Vexu** [Vexu/arocc#140]
```c
typedef struct {
  long long __clang_max_align_nonce1
      __attribute__((__aligned__(__alignof__(long long))));
  long double __clang_max_align_nonce2
      __attribute__((__aligned__(__alignof__(long double))));
} max_align_t;
```

**Comment by ehaas** [comment]
Should we be attaching record field attributes to the field's type, or should we be putting them somewhere else?

**Comment by Vexu** [comment]
Adding them to the fields type should be a good starting point. If it isn't correct we'll find out as a part of #42.
