### ISSUE TITLE
Crash: Addition expression: _Complex + integer

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#175]
```c
void foo(void) {
    (_Complex double)1 + 2;
}
```

```
thread 31081065 panic: reached unreachable code
/Users/ehaas/source/arocc/src/Parser.zig:4077:29: 0x105ff7946 in Parser.Result.add (arocc)
                    else => unreachable,
                            ^
/Users/ehaas/source/arocc/src/Parser.zig:4560:28: 0x105ff68be in Parser.addExpr (arocc)
                try lhs.add(plus.?, rhs, p);
                           ^
/Users/ehaas/source/arocc/src/Parser.zig:4517:28: 0x105ff58f4 in Parser.shiftExpr (arocc)
    var lhs = try p.addExpr();
                           ^
```

**Comment by ehaas** [comment]
C11 introduced as a conditional feature macro `__STDC_NO_COMPLEX__`: `The integer constant 1, intended to indicate that the implementation does not support complex types or the <complex.h> header.` - _Complex seems like it might be a lot of work; should we add that macro definition for now?

**Comment by Vexu** [comment]
> C11 introduced as a conditional feature macro `__STDC_NO_COMPLEX__`: `The integer constant 1, intended to indicate that the implementation does not support complex types or the <complex.h> header.` - _Complex seems like it might be a lot of work; should we add that macro definition for now?

We already define `__STDC_NO_COMPLEX__`, the issue also happends with `long double` so this would be a problem even without complex types.

**Comment by ehaas** [comment]
It seems like clang treats any expression that doesn't involve integers as unavailable - all of the following error with `static_assert expression is not an integral constant expression`:

```c
void foo(void) {
    _Static_assert(1.0f == 1.0f, "");
    _Static_assert((long double)1 + 1 == 2.0L, "");
    _Static_assert(1.0if, "");
    _Static_assert((_Complex long double)1, "");
    _Static_assert(1 + (int *)1 == 1 + (int *)1, "");
}
```
So perhaps we can get away with doing the same? This would also address #85

**Comment by ehaas** [comment]
Further perusal of the C11 standard shows me that the above only works because `_Static_assert` actually requires that all the elements of the condition be integer constants; clang actually does evaluate constant expressions with e.g. complex numbers:

```c
void foo(void) {
    const int x = (1.0f + (_Complex long double)1.0fi) - (1.0f + (_Complex long double)1.0fi);
    const int y = 1/x;
}
```
```
test.c:3:20: warning: division by zero is undefined [-Wdivision-by-zero]
    const int y = 1/x;
                   ^~
```

So I guess we need to add some entries to the `val` enum in `Result` - pointers to `f128` and `std.math.Complex(f128)` perhaps?

**Comment by Vexu** [comment]
> So I guess we need to add some entries to the `val` enum in `Result` - pointers to `f128` and `std.math.Complex(f128)` perhaps?

This is something I want to eventually do but for now I'll settle for not crashing.
