### ISSUE TITLE
Question: Alignment storage

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#23]
Note: this may be irrelevant if the plan is to move alignment out of the type itself and into an attributed type

Currently a `u29` is used to store the alignment but we could get away with a `u5` since the alignment must be a power of 2. 0 could be reserved for "no alignment specified", so we'd actually want to store `log_2(alignment) + 1`.  In this way a user-provided alignment of up to 2**30 could be supported.

https://github.com/Vexu/arocc/blob/6d0baf39d734078033d6f394f11bf09a1425ce82/src/Type.zig#L216

**Comment by Vexu** [comment]
This could be changed but it would currently make no difference as `alignment` fits snugly in the padding left by the other fields in `Type`.
