### ISSUE TITLE
Don't allow non-integer array sizes?

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#261]
Currently floats are allowed for array sizes (they are converted to ints) (https://github.com/Vexu/arocc/blob/9f8f4f405d81a116552b08f2756334da59fedf05/src/Parser.zig#L2381) but clang and gcc both disallow this. Can I remove the code that allows floats for array sizes?

**Comment by Vexu** [comment]
> Can I remove the code that allows floats for array sizes?

Yup, I added it as a result of crash in fuzzing (81d709461c65a2b59eb8ae17be2392480e3e3bb1)  and didn't check GCC/clang behavior.
