### ISSUE TITLE
attributes after decl are not being picked up in type.

### ISSUE THREAD

**Issue by TwoClocks** [Vexu/arocc#296]
I'm working on layout, and I'm having an issue picking up some attributes.

this works fine
`struct __attribute__ ((aligned (8))) S2 { int x; };`
but this does not
`struct S1 { int x; } __attribute__ ((aligned (8)));`

In Parse.zig I'm using ` p.withAttributes(ty, attr_buf_top)` to get the attributes, then inspecting them with `ty.requestedAlignment(p.pp.comp)`

I have two related questions :
1 - when I'm walking the fields in the record, I need to look at any attributes set for that field. How do I do this? I don't think `attr_buf_top` is pointing to the record, not the field.
2 - If I do layout for a type, how can I get the results of the layout if that type appears in another record? Currently, I'm just doing the layout again for the inner record. I'd like to just apply any attributes to the layout I've already done.

Thanks

**Comment by ehaas** [comment]
Are you working against the latest master branch? I believe I fixed that attribute bug:
```c
struct S1 { int x; } __attribute__ ((aligned (8)));
struct __attribute__ ((aligned (8))) S2 { int x; };
```
```
➜  ~ arocc --verbose-ast test.c
struct_decl_two: 'attributed(struct S1)'
 attr: aligned alignment: Attribute.Alignment{ .node = Tree.NodeIndex.none, .requested = 8, .alignas = false }
  record_field_decl: 'int'
   name: x

struct_decl_two: 'attributed(struct S2)'
 attr: aligned alignment: Attribute.Alignment{ .node = Tree.NodeIndex.none, .requested = 8, .alignas = false }
  record_field_decl: 'int'
   name: x
```

Attributes that happen after the closing `}` get parsed here: https://github.com/Vexu/arocc/blob/master/src/Parser.zig#L1707= so you'll have to do alignment after that.

`attr_buf_top` is just a way for the parser to manage its internal "attribute stack" of attributes that have been parsed and will need to be applied to the current type. So once you are iterating fields in a record, you shouldn't need to look at `attr_buf_top` - you can either call `getAttributes()` on the field's type to get them all, or call `getAttribute` with a comptime tag to get a specific attribute - e.g. `field.ty.getAttribute(.aligned)` would return a struct with a field called `alignment` of type `?Alignment` (see `Attribute.zig` for a definition of that)

For question #2 - do you mean extracting the already-computed `size` and `alignment` values of an existing record type?

**Comment by TwoClocks** [comment]
I'm current w/ master.

I was doing the layout about 5 lines before where you pointed to.  Where the current code just sets `size` and `alignment` to 1. I moved it after, and it's working. Had to change your asserts in attributes.c to the correct value to pass the tests :)

So all the fields are attributed at that point? After you call `p.attributeSpecifier()` ? Perfect.

nvm on question #2. I hadn't looked in the Record for the field type, so I was laying everything out again every time it was referred to by another record.
