### ISSUE TITLE
can't differentiate between attribute on type vs record field.

### ISSUE THREAD

**Issue by TwoClocks** [Vexu/arocc#300]
In this code
```c
typedef int a __attribute__((aligned(2)));
struct {
    a i;
} x;

struct {
    int i __attribute__((aligned(2)));
} y;

_Static_assert(sizeof(x) == 4, "");
_Static_assert(_Alignof(x) == 2, "");
_Static_assert(_Alignof(x.i) == 2, "");
_Static_assert(sizeof(y) == 4, "");
_Static_assert(_Alignof(y) == 4, "");
_Static_assert(_Alignof(y.i) == 4, "");
```

The record alignment is the max of the type alignment and the field alignment. So `x.i` has a field alignment of 0, and a type alignment of 2. So the size & align is 2. `y.i` has a field alignment of 2 and a type alignment of 4, so the size/align is 4.

Currently the ASTs for both are identical
```
struct_decl_two: 'struct (anonymous struct at ./loc-tests/current.c:2:1)'
  record_field_decl: 'attributed(int)'
   attr: aligned alignment: Attribute.Alignment{ .node = Tree.NodeIndex.none, .requested = 2, .alignas = false }
   name: i

var: 'struct (anonymous struct at ./loc-tests/current.c:2:1)'
 name: x

struct_decl_two: 'struct (anonymous struct at ./loc-tests/current.c:7:1)'
  record_field_decl: 'attributed(int)'
   attr: aligned alignment: Attribute.Alignment{ .node = Tree.NodeIndex.none, .requested = 2, .alignas = false }
   name: i
```

**Comment by ehaas** [comment]
I can tackle this one - I was thinking make the `fields` field in `Type.Record` be:
```zig
    fields: union(enum) {
        plain: [] Field,
        attributed: []AttributedField,
    },
```
where `AttributedField` looks like:
```zig
    pub const AttributedField = struct {
        name: []const u8,
        ty: Type,
        /// zero for anonymous fields
        name_tok: TokenIndex = 0,
        bit_width: u32 = 0,
        attributes: []const Attribute,

        pub fn isAnonymousRecord(f: Field) bool {
            return f.name_tok == 0 and f.ty.isRecord();
        }
    };
```

It increases the size of `Record` a bit but avoids paying a 16-byte penalty on each field for the common case where none of them have attributes.

**Comment by Vexu** [comment]
Another alternative would be to add a `[*][]const Attribute` field to `Type.Record`.

**Comment by ehaas** [comment]
It seems that if I use a regular union (instead of union enum) and add a `has_attributes: bool` to `Record` to manually track the active field, the size of `Record` stays at 48 bytes in `ReleaseFast` and `ReleaseSmall` (vs 56 bytes with the union enum). On the other hand your suggestion is much simpler to implement and less invasive of a change. Any preference?

**Comment by Vexu** [comment]
If you also think it's simpler then it's probably the way to go. It should also fit well into #310 based on a quick glance.

**Comment by TwoClocks** [comment]
YES! Went from excluding 34 test files from the layout tests to 9!
79 of the test cases working. Sweet!
