### ISSUE TITLE
Preprocessor misses some expansion opportunities

### ISSUE THREAD

**Issue by doppioandante** [Vexu/arocc#31]
```c
#define CREATE_CALL F
#define F(x) (x + 2)

CREATE_CALL(2)

#define EXPECTED_TOKENS (2 + 2)
```
This test case fails as arocc preprocessor generates `F ( 2 )`

**Comment by matu3ba** [comment]
Would a logging option of the applied preprocessors help for this kind of stuff? [clang does not provide logging macros etc](https://clang.llvm.org/docs/CommandGuide/clang.html#preprocessor-options), but I am not sure how complex this would be to dump the macro table, applied steps (and conditionally result).

Alternatively I found [ppstep](https://github.com/notfoundry/ppstep), which looks quite cool for debugging macros.
I am wondering, why nobody else wrote stuff to "debug macros" yet.

**Comment by doppioandante** [comment]
I didn't know about ppstep, having macro debugging inside arocc would be fun I think.
Doing that depends on implementing macros correctly first though, and this issue must be solved to do so.
