### ISSUE TITLE
Expose a build.zig option for linking libc?

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#326]
I've noticed a severe performance impact on the preprocessor from using `std.heap.GeneralPurposeAllocator` - I'm not super familiar with the zig build system, so maybe there's already a built-in way to do this, but it would be nice to add a build option to link libc so we can optionally use the raw c allocator.

Release fast build, running `arocc -E` on the sqlite3 amalgamated source (8 megs):

Using `std.heap.GeneralPurposeAllocator`:
`real	0m9.377s`

Linking libc so that `std.heap.raw_c_allocator` is used:
`real	0m0.314s`

For reference, using gcc on the same system:
`real	0m0.113s`

**Comment by Vexu** [comment]
> I'm not super familiar with the zig build system, so maybe there's already a built-in way to do this, but it would be nice to add a build option to link libc so we can optionally use the raw c allocator.

This can be copied directly from Zig's `build.zig` which has `force-link-libc`.

> Using `std.heap.GeneralPurposeAllocator`: `real 0m9.377s`

Oof.

> Linking libc so that `std.heap.raw_c_allocator` is used: `real 0m0.314s`
> 
> For reference, using gcc on the same system: `real 0m0.113s`

Not bad but looks like a plenty of optimization work is still needed, was this using `-c` or `-S` on gcc?

**Comment by ehaas** [comment]
These are the numbers I get (they are pretty consistent to within 5-10ms per run):
```
~$ time gcc -E sqlite3.c >/dev/null

real	0m0.114s
user	0m0.103s
sys	0m0.011s

~$ time gcc -S sqlite3.c

real	0m2.169s
user	0m2.096s
sys	0m0.064s

~$ time gcc -c sqlite3.c

real	0m2.337s
user	0m2.241s
sys	0m0.088s

~$ time gcc shell.c sqlite3.c -lpthread -ldl -lm -o sqlite3

real	0m2.816s
user	0m2.702s
sys	0m0.112s
```

**Comment by Vexu** [comment]
Oh, these were preprocessing numbers? I think I found one large reason for the slowness...
https://github.com/Vexu/arocc/blob/master/src/main.zig#L349-L349

**Comment by ehaas** [comment]
Yep, looks like that was causing a 50% slowdown. Consistently around `real	0m0.205s` on my system now. Halfway to GCC now :)
