### ISSUE TITLE
Alternative syntax for flexible arrays

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#327]
GCC and clang treat trailing one-element arrays at the end of structs as flexible arrays, because that's how people used to do it in C90. From my research it seems that it's one of those things that's technically undefined behavior according to the standard, but all (or most) vendors implement it the same way.

From https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html (emphasis mine):

> In the absence of the zero-length array extension, in ISO C90 the contents array in the example above would typically be declared to have a single element. Unlike a zero-length array which only contributes to the size of the enclosing structure for the purposes of alignment, a one-element array always occupies at least as much space as a single object of the type. **Although using one-element arrays this way is discouraged, GCC handles accesses to trailing one-element array members analogously to zero-length arrays.**

This construct is used in sqlite, so arocc currently issues some warnings that gcc & clang do not.

**Comment by ehaas** [comment]
Do you think we should introduce a new type specifier for trailing 1-element arrays, or just detect that sort of access in the parser?

**Comment by Vexu** [comment]
I doubt it'll be very useful to have a new type for that since the only place I can think of that it would help is in `checkArrayBounds` which should be disabled for zero length arrays anyways.
