### ISSUE TITLE
Optimization opportunity: inlining UTF8 functions in Tokenizer

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#333]
I set up Tracy to profile the `Tokenizer.next` function. On the sqlite3 source my computer spends about 103ms in `Tokenizer.next` (across approximately 2 million calls). I found that if I inlined the `utf8ByteSequenceLength` and `utf8Decode` functions by manually copying them from the Zig stdlib and removing the error branches (since we already know that the file is valid utf8 by the time we're tokenizing it) I was able to get it down to about 80ms.

Is that an optimization you'd want to pursue?

**Comment by andrewrk** [comment]
why does it need to decode UTF-8 at all?

**Comment by Vexu** [comment]
> Is that an optimization you'd want to pursue?

It sounds good, are there some downsides?

> why does it need to decode UTF-8 at all?

C standard supports [unicode identifiers](https://en.cppreference.com/w/c/language/identifier).
