### ISSUE TITLE
Preprocessor: __VA_OPT__ function macro

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#353]
Description here https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

clang only supports this in C++ mode with `-std=c++2a`. gcc supports it in all C standards but issues a pedantic warning `warning: __VA_OPT__ is not available until C++2a` in non-GNU standards.

Example usage:
```C
#define eprintf(format, ...) fprintf (stderr, format __VA_OPT__(,) __VA_ARGS__)
eprintf("test");
eprintf("test", 2);
```

After preprocessor expansion these become:
```
fprintf (stderr, "test" );
fprintf (stderr, "test" , 2);
```

**Comment by Vexu** [comment]
Implemented in caa78326e7777243db92a8d9b3070ec551f14393
