### ISSUE TITLE
`avr` long size wrong?

### ISSUE THREAD

**Issue by TwoClocks** [Vexu/arocc#366]
for target `avr-other-gnu` and this struct
```c
typedef struct {
    char c;
    long i:31 __attribute__((packed));
    long j:2;
} A8;
```
arocc errors with
```
0068_test.c:1665:10: error: width of bit-field exceeds width of its type
    long i:31 __attribute__((packed));
```

clang warns, about the packed attribute, but doesn't error.

is the size of a long for this platform set wrong?

**Comment by ehaas** [comment]
Looks like a bug in the Zig `CType` which I pulled in for sizeof calculations - it's saying that a long is 2 bytes, which is not a valid size for a long in C (must be capable of containing at least `[−2,147,483,647, +2,147,483,647]`)

You can see this with plain Zig:
```zig
const std = @import("std");
export fn foo() void {
    comptime {
        std.debug.assert(@sizeOf(c_long) >= 4);
    }
}
```

`zig build-obj -target avr-freestanding-none test.zig`

**Comment by ehaas** [comment]
Reported upstream https://github.com/ziglang/zig/issues/12328
