### ISSUE TITLE
Should not warn if control flow reaches closing `}` of main

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#368]
Since C99, if the return type of `main` is compatible with `int` and control flow reaches the closing `}`, then `main` implicitly returns 0. GCC and clang issue no warnings.

Skipping the warning is easy enough, but how should we handle the AST - it looks like `.implicit_return` nodes don't have any associated data. Should we have a separate node type for `implicit_main_return`?

**Comment by Vexu** [comment]
> Skipping the warning is easy enough, but how should we handle the AST - it looks like `.implicit_return` nodes don't have any associated data. Should we have a separate node type for `implicit_main_return`?

`implicit_return` also doesn't use any of the fields in `Node.data` so it would be easy to add a bool there.

**Comment by ehaas** [comment]
Just a zero, it's in section `5.1.2.2.3` 

```
If the return type of the main function is a type compatible with int, a return from the
initial call to the main function is equivalent to calling the exit function with the value
returned by the main function as its argument; reaching the } that terminates the
main function returns a value of 0. If the return type is not compatible with int, the
termination status returned to the host environment is unspecified.
```

**Comment by Vexu** [comment]
> Just a zero, it's in section `5.1.2.2.3`

Huh, I guess I was mixing it up with some other gotcha. Do we then actually need to differentiate between this and a regular `implicit_return`, they should be perfectly identical in every way except that one didn't give an error.

**Comment by ehaas** [comment]
So just always treat `implicit_return` as if it's returning an integer 0? I think that would work.

**Comment by Vexu** [comment]
> So just always treat `implicit_return` as if it's returning an integer 0? I think that would work.

Looks like I was also mixing up `implicit_return` and `default_init_expr` or something... Ok, I think adding a `return_zero` field to `Node.Data` used by `implicit_return` is a good way to go here.
