### ISSUE TITLE
Preprocessor: preprocessing numbers not always handled correctly

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#391]
The following should be a syntax error:
```c
_Static_assert(0xE+0xC == 0xE + 0xC, "");
```
Because `0xE+0xC` is a single "preprocessing number" (Section 6.4.8).

From the GCC docs:

> A preprocessing number has a rather bizarre definition. The category includes all the normal integer and floating point constants one expects of C, but also a number of other things one might not initially recognize as a number. Formally, preprocessing numbers begin with an optional period, a required decimal digit, and then continue with any sequence of letters, digits, underscores, periods, and exponents. Exponents are the two-character sequences ‘e+’, ‘e-’, ‘E+’, ‘E-’, ‘p+’, ‘p-’, ‘P+’, and ‘P-’. (The exponents that begin with ‘p’ or ‘P’ are used for hexadecimal floating-point constants.)

**Comment by Vexu** [comment]
Related  #143
