### ISSUE TITLE
missing libc header: stdio.h

### ISSUE THREAD

**Issue by nektro** [Vexu/arocc#426]
musl's example https://git.musl-libc.org/cgit/musl/tree/include/stdio.h

**Comment by Vexu** [comment]
`Compilation.defineSystemIncludes` doesn't handle `NIX_CFLAGS_COMPILE` and many other things yet.

**Comment by RossComputerGuy** [comment]
To use arocc with nix properly, you have to pass it to `wrapCCWith { cc = arocc; }`. However, we're looking to get arocc into nixpkgs upstream so this will not be an issue. Of course, arocc is free to implement support for nix and not rely on the wrapper.

**Comment by RossComputerGuy** [comment]
Arocc is in nixpkgs upstream and the CC wrapper appears to be working with it. I believe this issue could be closed now.

**Comment by Vexu** [comment]
I trust you to know nix better than me.
