### ISSUE TITLE
_Complex __fp16 - remove?

### ISSUE THREAD

**Issue by ehaas** [Vexu/arocc#454]
Neither clang nor GCC support this type, but arocc does:

```C
test.c:3:5: error: '_Complex half' is invalid
    _Complex __fp16 x;
    ^
```

I was going to start implementing `_Float16` support; Clang and GCC also do not support `_Complex _Float16` - should I remove `_Complex __fp16`? Or also implement `_Complex _Float16`?

**Comment by ehaas** [comment]
https://github.com/llvm/llvm-project/blob/main/clang/include/clang/AST/Type.h#L7196

**Comment by Vexu** [comment]
Either way works for me but since I already followed clang and GCC on disallowing `__int128` on some targets we should probably match that here.
