### ISSUE TITLE
Backslashes should be escaped in `#line` directive filenames

### ISSUE THREAD

**Issue by squeek502** [Vexu/arocc#553]
All of the below uses the following as `foo.c` (doesn't really matter what's in this file):
```c
foo
```

Current behavior:
```
> arocc -E .\foo.c
# 1 ".\foo.c" 1
# 1 "<builtin>" 1
# 186 "<builtin>"
# 1 "<command line>" 1
# 1 ".\foo.c" 2
foo
```

Expected behavior:

```
> arocc -E .\foo.c
# 1 ".\\foo.c" 1
# 1 "<builtin>" 1
# 186 "<builtin>"
# 1 "<command line>" 1
# 1 ".\\foo.c" 2
foo
```

The expected behavior matches clang:

```
> clang -E -xc .\foo.c
# 1 ".\\foo.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 368 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 ".\\foo.c" 2
foo
```

and `rc.exe`'s preprocessor, too (so it should always escape `\` even with `--emulate=msvc`:

```
> rc.exe /p .\foo.c
#line 1 "C:\\Users\\Ryan\\Programming\\Zig\\resinator\\tmp\\RCa03024"
#line 1 ".\\foo.c"
#line 1 ".\\foo.c"
foo
```

---

Unsure about other characters that should be escaped, might want to do something similar to `std.zig.fmtEscapes`

**Comment by Vexu** [comment]
Here's where that is printed:

https://github.com/Vexu/arocc/blob/e95f60c4f0a899c227a128f6f9071f3e08c974b8/src/aro/Preprocessor.zig#L3062

**Comment by squeek502** [comment]
Here's a potentially naive patch based on `std.zig.fmtEscapes`:

```patch
 src/aro/Preprocessor.zig | 29 ++++++++++++++++++++++++++++-
 1 file changed, 28 insertions(+), 1 deletion(-)

diff --git a/src/aro/Preprocessor.zig b/src/aro/Preprocessor.zig
index cd86239..c8870c8 100644
--- a/src/aro/Preprocessor.zig
+++ b/src/aro/Preprocessor.zig
@@ -3049,6 +3049,33 @@ fn findIncludeSource(pp: *Preprocessor, tokenizer: *Tokenizer, first: RawToken,
         pp.fatal(first, "'{s}' not found", .{filename});
 }
 
+fn linemarkerPathEscape(
+    bytes: []const u8,
+    comptime fmt: []const u8,
+    options: std.fmt.FormatOptions,
+    writer: anytype,
+) !void {
+    _ = fmt;
+    _ = options;
+    for (bytes) |byte| switch (byte) {
+        '\n' => try writer.writeAll("\\n"),
+        '\r' => try writer.writeAll("\\r"),
+        '\t' => try writer.writeAll("\\t"),
+        '\\' => try writer.writeAll("\\\\"),
+        '"' => try writer.writeAll("\\\""),
+        ' ', '!', '#'...'&', '('...'[', ']'...'~' => try writer.writeByte(byte),
+        // Use hex escapes for rest any unprintable characters.
+        else => {
+            try writer.writeAll("\\x");
+            try std.fmt.formatInt(byte, 16, .lower, .{ .width = 2, .fill = '0' }, writer);
+        },
+    };
+}
+
+pub fn fmtLinemarkerPath(bytes: []const u8) std.fmt.Formatter(linemarkerPathEscape) {
+    return .{ .data = bytes };
+}
+
 fn printLinemarker(
     pp: *Preprocessor,
     w: anytype,
@@ -3059,7 +3086,7 @@ fn printLinemarker(
     try w.writeByte('#');
     if (pp.linemarkers == .line_directives) try w.writeAll("line");
     // line_no is 0 indexed
-    try w.print(" {d} \"{s}\"", .{ line_no + 1, source.path });
+    try w.print(" {d} \"{s}\"", .{ line_no + 1, fmtLinemarkerPath(source.path) });
     if (pp.linemarkers == .numeric_directives) {
         switch (start_resume) {
             .none => {},
```

Let me know if you'd like me to submit it as a PR.

**Comment by Vexu** [comment]
I'd inline that for loop in `printLinemarker` but that does seem good. Have you checked how other compilers handle unprintable characters? You'd at least want to avoid printing unicode characters as hex escapes.

**Comment by squeek502** [comment]
filename: `кириллица.c`, current codepage: 65001 (UTF-8)

clang outputs non-ASCII bytes as octal escapes (`clang -E -xc кириллица.c`):
```
# 1 "\320\272\320\270\321\200\320\270\320\273\320\273\320\270\321\206\320\260.c" 2
```

`rc.exe` outputs a UTF-16 encoded file, so this is UTF-16:
```
#line 1 "кириллица.c"
```

with the above patch, `arocc -E кириллица.c` gives:
```
# 1 "\xd0\xba\xd0\xb8\xd1\x80\xd0\xb8\xd0\xbb\xd0\xbb\xd0\xb8\xd1\x86\xd0\xb0.c" 2
```

I think using escapes might make sense here, since in theory the 'correct' solution would be to match the encoding of the input file, but that is effectively impossible in the general sense since not all encodings support all Unicode codepoints (e.g. кириллица couldn't be represented in Windows-1252). By using escapes, we ensure that the bytes of the *parsed* string are consistent regardless of what the parser thinks the encoding is.

(`.rc` files make this even trickier, since they have support for multiple encodings per file [each line can have a totally different encoding, essentially])
