### ISSUE TITLE
Linker errors on Arch Linux

### ISSUE THREAD

**Issue by Vexu** [Vexu/arocc#558]
```sh-session
$ echo "int main(void) { return 0; }" > main.c
$ arocc main.c
/usr/bin/ld: cannot find crtbegin.o: No such file or directory
/usr/bin/ld: cannot find -lgcc: No such file or directory
/usr/bin/ld: cannot find -lgcc: No such file or directory
fatal error: linker exited with an error code
1 error generated.
```

**Comment by ehaas** [comment]
I think some arguments might be switched around here: https://github.com/Vexu/arocc/blob/0f4aa86fc15a74fe859f17913bc24e63643f8d60/src/aro/Driver/GCCDetector.zig#L412

Can you try changing that line to `try collectLibDirsAndTriples(tc, &candidate_lib_dirs, &candidate_triple_aliases, &candidate_biarch_lib_dirs,  &candidate_biarch_triple_aliases);`
