### ISSUE TITLE
typo in loadAll function

### ISSUE THREAD

**Issue by ziereis** [Vexu/arocc#636]
when trying to compile with zig build  you get the error:

install
└─ install arocc
   └─ zig build-exe arocc Debug native 1 errors
src/aro/Compilation.zig:72:17: error: expected type 'error{OutOfMemory,InvalidUtf8,EnvironmentVariableNotFound}', found 'error{InvalidWtf8}'
                error.InvalidWtf8 => null,
                ^~~~~~~~~~~~~~~~~
src/aro/Compilation.zig:72:17: note: 'error.InvalidWtf8' not a member of destination error set

easily fixed by changing the W to a U

**Comment by ehaas** [comment]
I believe this is because you're using an older version of zig; that error was added recently. However I just saw that there is a different error with the latest version of the compiler, I'll send a PR for that soon.

**Comment by ehaas** [comment]
@ziereis if you download the latest version of zig (I'm on `0.12.0-dev.3074+ae7f3fc36`) + pull in the latest from this repo you should be able to build it.

**Comment by ehaas** [comment]
Let me know if you have any other trouble getting it to compile.
