### ISSUE TITLE
Aro's generated modules have generic names that flow to consuming projects

### ISSUE THREAD

**Issue by alexrp** [Vexu/arocc#713]
In a project where I consume Aro's module, I noticed that I get this in `zig build-exe` invocations:

```
zig build-exe ... --dep aro --dep system_defaults --dep build_options --dep backend --dep Builtins/Builtin.def --dep Attribute/names.def --dep Diagnostics/messages.def -Maro=.../aro.zig -Msystem_defaults=.../options.zig -Mbuild_options=.../options.zig --dep build_options -Mbackend=.../backend.zig -MBuiltins/Builtin.def=.../Builtin.zig -MAttribute/names.def=.../names.zig -MDiagnostics/messages.def=.../messages.zig ...
```

It's not *currently* problematic, but the names `build_options`, `backend`, and `system_defaults` in particular seem generic enough that they could cause problems in the future. Would it make sense to rename these to have an `aro_` prefix?

**Comment by Vexu** [comment]
Aren't the modules namespaced in the build system?

**Comment by alexrp** [comment]
You're right; I didn't realize that's how `-M` works. Sorry for the noise!
